[package]
name = "papyrus"
version = "0.1.0"
authors = ["Peter Coleman <peter.coleman143@gmail.com>"]

[dependencies]
csv = "1"
unicode-normalization = "0.1.7"
caseless = "0.2.1"
iron = "0.6.0"
router = "0.6.0"